"""Generate the enlace app directory that serves a connector.

A connector with heavy dependencies (ML models, large libraries) should not be
mounted in-process with the rest of the platform — it runs as an enlace
``mode="process"`` app: enlace spawns it as a supervised subprocess in its **own
venv** and reverse-proxies the route to it. This module renders that app dir — an
``app.toml`` (access=public, mode=process, route) and a ``server.py`` that builds
the connector app from its :class:`~enlace_connector.connector.ConnectorSpec`.

The connector authenticates clients itself (bearer JWTs), so at the enlace layer it
is ``access="public"`` — enlace does not gate it with session cookies.
"""

from __future__ import annotations

from pathlib import Path

from .connector import ConnectorSpec

__all__ = ["render_app_toml", "render_server_py", "scaffold_app"]

#: Default platform origin used as the OAuth issuer when none is set in the env.
DFLT_PLATFORM_ORIGIN = "https://apps.thorwhalen.com"


def render_app_toml(
    spec: ConnectorSpec,
    *,
    port: int,
    command: str | None = None,
) -> str:
    """Render the enlace ``app.toml`` for *spec* as a ``mode="process"`` app."""
    cmd = command or f"uvicorn server:app --host 127.0.0.1 --port {port}"
    return (
        "# Auto-generated by enlace_connector — a Claude.ai MCP connector served as a\n"
        "# mode=process enlace app (its own venv carries the heavy tool deps). The\n"
        "# connector validates bearer tokens itself, so enlace treats it as public.\n"
        f'display_name = "{spec.server_name}"\n'
        'access = "public"\n'
        'mode = "process"\n'
        f'command = "{cmd}"\n'
        f"port = {port}\n"
        f'route = "{spec.mount_route}"\n'
    )


def render_server_py(spec: ConnectorSpec) -> str:
    """Render the ``server.py`` that exposes ``app`` for enlace's process runner."""
    return (
        f'"""Auto-generated enlace connector app for {spec.name!r}.\n\n'
        "Built from a ConnectorSpec by enlace_connector. The platform origin (the\n"
        "OAuth issuer) is read from $CONNECTOR_ISSUER; this connector's public URL\n"
        '(the token audience) is derived from it and the route.\n"""\n\n'
        "import os\n\n"
        "from enlace_connector import ConnectorSpec, make_connector_app\n\n"
        "SPEC = ConnectorSpec(\n"
        f"    name={spec.name!r},\n"
        f"    tools={spec.tools!r},\n"
        f"    auth={spec.auth!r},\n"
        f"    title={spec.title!r},\n"
        f"    route={spec.route!r},\n"
        ")\n\n"
        f"_issuer = os.environ.get('CONNECTOR_ISSUER', {DFLT_PLATFORM_ORIGIN!r})\n"
        "app = make_connector_app(SPEC, issuer=_issuer)\n"
    )


def scaffold_app(
    spec: ConnectorSpec,
    dest_dir: str | Path,
    *,
    port: int,
    command: str | None = None,
) -> dict[str, Path]:
    """Write ``app.toml`` and ``server.py`` for *spec* into *dest_dir*.

    *dest_dir* is the enlace app directory (e.g. ``tw_platform/apps/<name>``).
    Returns the paths written. Creates *dest_dir* if needed; overwrites the two
    generated files (they are derived artifacts).
    """
    dest = Path(dest_dir)
    dest.mkdir(parents=True, exist_ok=True)
    app_toml = dest / "app.toml"
    server_py = dest / "server.py"
    app_toml.write_text(
        render_app_toml(spec, port=port, command=command), encoding="utf-8"
    )
    server_py.write_text(render_server_py(spec), encoding="utf-8")
    return {"app_toml": app_toml, "server_py": server_py}
